eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: clientName2
    prefer-ip-address: true
spring:
  application:
    name: eurekaClient_fegin
server:
  port: 8763
